keep_features:
  - Flow Duration
  - Flow Byts/s
  - Flow Pkts/s
  - Tot Fwd Pkts
  - Tot Bwd Pkts
  - Pkt Len Mean
  - Pkt Len Std
  - Fwd Pkt Len Mean
  - Bwd Pkt Len Mean
  - Flow IAT Mean
  - Flow IAT Std
  - Fwd IAT Mean
  - Bwd IAT Mean
  - SYN Flag Cnt
  - ACK Flag Cnt
  - RST Flag Cnt
  - Down/Up Ratio
