version: 1
name: label_normalization_contract
source_column: label
target_column: label_norm
mappings:
- raw_label: 'Benign'
  normalized_label: 'benign'
- raw_label: 'Bot'
  normalized_label: 'bot'
- raw_label: 'Brute Force -Web'
  normalized_label: 'brute_force_web'
- raw_label: 'Brute Force -XSS'
  normalized_label: 'brute_force_xss'
- raw_label: 'DDOS attack-HOIC'
  normalized_label: 'ddos_attack_hoic'
- raw_label: 'DDOS attack-LOIC-UDP'
  normalized_label: 'ddos_attack_loic_udp'
- raw_label: 'DDoS attacks-LOIC-HTTP'
  normalized_label: 'ddos_attacks_loic_http'
- raw_label: 'DoS attacks-GoldenEye'
  normalized_label: 'dos_attacks_goldeneye'
- raw_label: 'DoS attacks-Hulk'
  normalized_label: 'dos_attacks_hulk'
- raw_label: 'DoS attacks-SlowHTTPTest'
  normalized_label: 'dos_attacks_slowhttptest'
- raw_label: 'DoS attacks-Slowloris'
  normalized_label: 'dos_attacks_slowloris'
- raw_label: 'FTP-BruteForce'
  normalized_label: 'ftp_bruteforce'
- raw_label: 'Infilteration'
  normalized_label: 'infiltration'
- raw_label: 'SQL Injection'
  normalized_label: 'sql_injection'
- raw_label: 'SSH-Bruteforce'
  normalized_label: 'ssh_bruteforce'
enum_final:
- 'benign'
- 'bot'
- 'brute_force_web'
- 'brute_force_xss'
- 'ddos_attack_hoic'
- 'ddos_attack_loic_udp'
- 'ddos_attacks_loic_http'
- 'dos_attacks_goldeneye'
- 'dos_attacks_hulk'
- 'dos_attacks_slowhttptest'
- 'dos_attacks_slowloris'
- 'ftp_bruteforce'
- 'infiltration'
- 'sql_injection'
- 'ssh_bruteforce'
